# Generated by Django 3.0.1 on 2019-12-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title',
            field=models.TextField(default='Null'),
            preserve_default=False,
        ),
    ]
