# Generated by Django 3.0.1 on 2019-12-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GetCatchment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('X', models.FloatField()),
                ('Y', models.FloatField()),
                ('uploadfolder', models.CharField(max_length=50)),
                ('userfolder', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=50)),
            ],
        ),
    ]
