# Generated by Django 3.0.1 on 2019-12-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catchment', '0002_getcatchment_catchment_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='getcatchment',
            name='ip',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
